[tox]
envlist =
    lint,
    py310,
    py311,
    py312,
    py313,
    py314,
    #py314t,

[testenv]
runner = uv-venv-lock-runner
uv_python_preference = only-managed
uv_sync_flags = --all-extras
dependency_groups = test
passenv = UV_LINK_MODE
setenv =
    APP_ENV = {env:APP_ENV:local}
    COVERAGE_FILE = .coverage_db_{envname}
commands = 
    pytest \
      --color=yes \
      --cov=opapywasm \
      --cov-report html:htmlcov_{envname} \
      --cov-report term \
      --cov-report xml:coverage_{envname}.xml

[testenv:lint]
dependency_groups = dev, test
commands =
    ruff --version
    ruff check .
    isort --version
    isort --check-only --df .
    black --version
    black --check --diff .
    mypy --version
    mypy .
