blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/intuit/opa-py-wasm/discussions
    about: Ask a question or discuss an idea with the maintainers and community.
